title: <p align="center"> Amr Alfayoumy </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Cairo, Egypt
  <br> +201026286004
  <br> amr.alfayoumy@outlook.com
  <br> <a href="pdf/Amr_Alfayoumy.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alfayoumy/">LinkedIn</a> |
  <a href="https://github.com/alfayoumy">GitHub</a>
  
  <p align="justify">
  I am a <b>data scientist</b> who enjoys drawing insights from data and thinks data always has a better idea. 
  <br>
  I have graduated summa cum laude with a <b>Bachelor's Degree in Computer Engineering (CGPA of 3.92) from Nile University</b>
  <br>
  I have also completed various data science and AI courses via <b>Coursera</b>, <b>Udacity</b>, and others.
  <br>
  I consider myself a passionate, hard-working, and determined person. I am also a fast-learner with a creative attitude to problem-solving.
  <br>
  My ultimate goal in life is to <b>use AI to make the world a better place for all humanity</b>.
  <br>
  </p>
  
theme: jekyll-theme-minimal