title: <p align="center"> Amr Alfayoumy </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Cairo, Egypt
  <br> +201026286004
  <br> amr.alfayoumy@outlook.com
  <br> <a href="pdf/Amr_Alfayoumy.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alfayoumy/">LinkedIn</a> |
  <a href="https://github.com/alfayoumy">GitHub</a>
  
  <p align="justify">
  I am a <b>data scientist</b> who enjoys connecting the dots by the use of technology. 
  <br>
  I have graduated with a <b>Master's Degree in Data Science at University of Milano-Bicocca</b>, where I received solid training in all the major fields of Data Science.
  <br>
  I have a hard science education, having achieved a <b>Bachelor's Degree in Chemical Sciences and Technologies</b>.
  <br>
  I consider myself a kind, empathetic, creative and determined person. I am pragmatic and organized, yet flexible.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal