title: <p align="center"> Amr Alfayoumy </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Cairo, Egypt
  <br> +201026286004
  <br> amr.alfayoumy@outlook.com
  <br> <a href="pdf/Amr_Alfayoumy.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/alfayoumy/">LinkedIn</a> |
  <a href="https://github.com/alfayoumy">GitHub</a>
  
  <p align="justify">
  I am a <b>data scientist</b> who enjoys drawing knowledge and insights from data and thinks data always has a better idea. 
  <br>
  I have graduated summa cum laude with a <b>Bachelor's Degree in Computer Engineering (CGPA of 3.92) from Nile University</b>, where I received solid training in all the major fields of computer engineering.
  <br>
  During the course of my career, I managed to accrue over 3 years of work experience and developed an interest in Data Science and AI. To develop my interest even further, I have acquired multiple certificates for various data science and AI courses via Coursera, Udacity, and others (listed below in the Certificates section).
  <br>
  I consider myself a passionate, hard-working, empathetic, and determined person. I am also a fast-learner with a creative attitude to problem-solving. To put it simply, I am pragmatic and organized, yet flexible.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal